version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-for-tag
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: admin
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./tmp/docker/mysql:/var/lib/mysql
