server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8}
    username: ${DB_USER_NAME:admin}
    password: ${DB_USER_PASSWORD:admin}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    authorization-grant-type: authorization_code
    url:
      protocol: https
      auth-host: kauth.kakao.com
      api-host: kapi.kakao.com
