name: Build & Unit Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set JDK to 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          java-package: jdk
          architecture: x64
          cache: 'gradle'

      - name: Build with Gradle
        run: |
          ./gradlew clean build

      - name: Run Unit Tests
        run: |
          ./gradlew unit-test:test

      - name: docker image build
        run: docker build -t anwjdrbs123/tag-wonder-api-ci .

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker Hub push
        run: docker push anwjdrbs123/tag-wonder-api-ci
